# Generated by Django 4.1.3 on 2022-11-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='sold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
